/*
  # PR-23: Convert pr-22d blog content from Markdown to HTML

  The site's BlogPostPage.tsx component renders blog content via
  dangerouslySetInnerHTML wrapped in a `prose prose-lg prose-invert` container
  (@tailwindcss/typography). Earlier migrations for this slug stored the body
  as raw Markdown, which rendered as a single unformatted text blob since the
  browser does not parse `##`, `**`, or `[text](/link)` syntax.

  This migration replaces the Markdown body with clean semantic HTML (h2, h3,
  p, ul, li, strong, em, a, table). The typography plugin handles styling.

  Idempotent: UPDATE by slug.
*/

UPDATE blog_posts
SET content = $BODY$<h2>Key Takeaways</h2>
<ul>
<li>Roof pitch measures how steeply your roof rises, expressed as inches of vertical rise per 12 inches of horizontal run. A 4:12 pitch rises 4 inches over every foot.</li>
<li>Steeper roofs shed water faster, which matters when South Florida storms drop 1–3 inches of rain in under an hour. Flat and low-slope roofs rely on membrane waterproofing and engineered drainage rather than shedding.</li>
<li>Material compatibility depends on pitch: most architectural shingles require at least 2:12 with enhanced underlayment, most tile needs 4:12 or steeper, and flat roofs (0:12–1:12) must use membrane systems like TPO, PVC, or modified bitumen.</li>
<li>The Florida Building Code sets minimum slopes for specific assemblies — for example, exposed-fastener metal panel roofing generally requires at least 3:12 per FBC 1507.4.</li>
<li>Changing your roof&rsquo;s pitch during a standard replacement is usually a structural project, not a simple upgrade.</li>
<li>All Phase Construction evaluates pitch, drainage, and material compatibility on every estimate. Regular inspections and keeping drains clear of debris are essential to preventing costly repairs.</li>
</ul>
<h2>Introduction: Why Roof Pitch Is More Than Curb Appeal</h2>
<p>Roof pitch is one of the most consequential design choices in a home, and it is also one of the most invisible. Most South Florida homeowners think of pitch as an aesthetic detail — a taller roofline looks more traditional, a flatter one looks more modern. But pitch is really physics: how fast water sheds off your roof surface, what roofing materials you can install, how your roof handles a Broward or Palm Beach downpour, and how it performs in a hurricane.</p>
<p>In our region, pitch decisions interact with heavy rainfall from afternoon thunderstorms, Florida Building Code requirements, and insurance expectations. Getting pitch wrong — or not understanding what you already have — is one of the more expensive mistakes a homeowner can make during building design or remodeling. Proper drainage is essential for preventing water damage and extending the life of the structure.</p>
<p>This guide breaks down what pitch actually means, how it affects drainage and material choices, and what South Florida homeowners should consider before their next <a href="/roof-replacement">roof replacement</a> or major remodel.</p>
<h2>What Roof &ldquo;Pitch&rdquo; Actually Means</h2>
<p>Pitch describes the steepness of your roof, typically expressed as the vertical rise in inches for every 12 inches of horizontal run. A 4:12 pitch means your roof rises 4 inches over every foot of horizontal distance. The 12-inch run is the standard reference across the industry.</p>
<p>You may hear &ldquo;pitch,&rdquo; &ldquo;slope,&rdquo; and &ldquo;rise-over-run&rdquo; used interchangeably. Technically, slope refers to rise per unit run while true pitch historically meant rise over the full span between walls. In modern practice, most contractors and homeowners use these terms the same way. Percentage grade is a mathematical conversion — a 6:12 pitch equals roughly 50% slope — but the x:12 format is what you will see on plans and estimates.</p>
<p>Contractors measure pitch on-site using a 12-inch level placed horizontally on the roof deck or rafter and then measuring the vertical distance at the level&rsquo;s end. Specialized pitch gauges and smartphone apps provide quick reads, but experienced roofers verify with a framing square.</p>
<p>Florida roofs generally fall into four practical categories. <strong>Flat roofs</strong> (0:12 to 1:12) appear on many Fort Lauderdale mid-century homes, additions, and commercial structures. <strong>Low-slope roofs</strong> (1:12 to 4:12) are common on 1960s–1970s ranches, Mediterranean revivals, and modern homes, and they are particularly vulnerable to ponding if drainage is not engineered correctly. <strong>Medium-slope roofs</strong> (4:12 to 8:12) define typical Parkland or Wellington subdivisions. <strong>Steep-slope roofs</strong> (8:12 and above) show up on older Mediterranean estates, custom waterfront homes, and architectural gables. These bands guide drainage design, material selection, and code compliance.</p>
<h2>Why Roof Pitch Matters So Much for Drainage</h2>
<p>Gravity moves water faster on steeper roofs. On a shallow 2:12 slope, water velocity drops dramatically, and any drainage obstruction quickly leads to pooling.</p>
<p>South Florida&rsquo;s convective thunderstorms regularly deliver 1–3 inches of rain in under an hour. Your roof has to handle these peaks without allowing standing water. Steeper roofs rely on momentum — overlapping shingles, tile, or metal panels channel water downslope before it can penetrate seams. Flat and low-slope roofs take a different approach entirely.</p>
<p>Flat roof systems depend on continuous membrane waterproofing rather than shedding. They require tapered insulation to create a slight pitch toward drains, crickets around penetrations, and properly sized scuppers and drains. Without an intentional drainage design, water sits on the membrane and finds weak points.</p>
<p>Ponding water — standing water that remains more than 48 hours after rain — is the primary enemy of low-slope roofs. It accelerates adhesive breakdown, stresses seams, and adds structural load. One inch of standing water weighs roughly 5 pounds per square foot. Even a modest puddle across a large flat roof adds real weight that the structure was not designed to hold long-term.</p>
<p>The Florida Building Code requires a minimum slope even on &ldquo;flat&rdquo; roofs — generally at least 1/4 inch per foot — to prevent water accumulation and structural damage.</p>
<h2>Material Compatibility by Roof Pitch</h2>
<p>Not every roofing material works on every pitch. Manufacturer warranties strictly limit installation slopes, and ignoring those limits leads to wicking leaks and voided coverage.</p>
<p>For flat roofs (0:12–1:12), only membrane systems are appropriate: TPO, PVC, modified bitumen, or built-up roofing. Built-up roofing (BUR) consists of multiple layers of waterproof material alternated with hot bitumen and finished with a ballast layer such as stone. Modified bitumen is a flexible asphalt-based sheet installed with either a torch-down or self-adhered method. Single-ply membranes like TPO and EPDM form a continuous waterproof barrier and are widely used on modern flat-roofed homes and commercial structures. Shingles and tile cannot be installed on flat or near-flat roofs because water will sit and wick under the laps, producing leaks within seasons.</p>
<p>Low-slope roofs from 1:12 to 2:12 still generally require membrane systems or specially rated low-slope shingles with a double underlayment per the manufacturer&rsquo;s instructions.</p>
<p>Between 2:12 and 4:12, architectural shingles become viable with enhanced underlayment. Standing-seam metal performs well in this range. Tile remains risky — many profiles require 4:12 minimum, and installing tile on too shallow a pitch invites capillary wicking regardless of underlayment quality.</p>
<p>Medium-slope roofs from 4:12 to 8:12 are the sweet spot for South Florida materials. Architectural shingles, concrete and clay tile, standing-seam metal, and synthetic shakes all work when installed to manufacturer specifications.</p>
<p>Steep-slope roofs at 8:12 and above use the same materials but require enhanced fastening schedules and sometimes different warranty provisions above 9:12.</p>
<p>We install all of these systems, and we always confirm the pitch and manufacturer requirements before recommending any material for your <a href="/roof-replacement">roof replacement</a> or repair.</p>
<h2>Pitch and Hurricane Performance in Broward and Palm Beach</h2>
<p>Both flat and pitched roofs have to be designed for high winds across South Florida, and pitch interacts with wind differently than it does with water.</p>
<p>Flat roofs face maximum uplift at perimeters and corners, where wind pressures can be significantly higher than on the field of the roof. That is why fully-adhered membranes, perimeter fastening, and proper edge metal matter so much on flat roofs. Medium and steep-slope roofs catch more wind on the face but shed pressure differently. In both cases, fastening schedules and edge detailing usually matter more than pitch alone.</p>
<p>High-wind-rated materials available for South Florida include metal systems achieving 150–180+ mph ratings, Class H shingles rated to approximately 150 mph, and Miami-Dade NOA-approved tile systems reaching 150+ mph when installed correctly with foam adhesives.</p>
<p>Broward County lies within the High Velocity Hurricane Zone (HVHZ), which requires stricter testing and product approvals than Palm Beach County. Palm Beach is not in HVHZ but still enforces high-wind ratings and rigorous permitting for roofing work.</p>
<p>For the deeper engineering details on fastening, uplift, and wind ratings, see our guide on <a href="/blog/what-makes-a-roof-hurricane-resistant">what makes a roof hurricane-resistant</a>. A well-designed roof can achieve excellent hurricane performance at a range of pitches when it is built to code.</p>
<h2>Drainage Specifics for Flat and Low-Slope Roofs</h2>
<p>Flat roofs are common on South Florida homes and additions, but they demand intentional drainage design to stay watertight under heavy rainfall.</p>
<p>Tapered polyiso insulation creates subtle slopes (typically 1/4 inch per foot minimum) directing water toward primary drains. Crickets — small wedged diverters — behind HVAC curbs, skylights, and chimneys redirect flow around penetrations rather than letting water collect against them.</p>
<p>Most flat roof leaks originate at penetration and edge details — curbs, flashings, and terminations — rather than in the field of the membrane itself. Experienced roofing crews focus heavily on these transitions because they handle the most stress during storms.</p>
<p>On residential flat roofs in Broward and Palm Beach, primary drainage is typically some combination of interior drains, scuppers at the roof edge, and overflow scuppers installed slightly higher than the primary outlets. Primary drains (often 4-inch strainers) handle normal storms, while overflow scuppers give excess water somewhere to go if a primary drain clogs. Gutters work for low-slope residential edges but can clog quickly with palm fronds and debris.</p>
<p>If you own an older flat roof, regular inspections catch ponding, clogged drains, and failing seams before they become active leaks. A <a href="/roof-inspection">roof inspection</a> is the right starting point if you are not sure how your current drainage is performing.</p>
<h2>Common Roof Pitch and Drainage Mistakes</h2>
<p>Many serious roof problems in South Florida trace back to decisions that ignored pitch and drainage limitations.</p>
<p>Assuming you can significantly change roof pitch during a routine re-roof is a common expensive surprise. Meaningful pitch changes require new trusses, modified wall heights, engineered drawings, and additional permits — they are structural projects, not shingle swaps.</p>
<p>Installing the wrong material for the wrong pitch causes predictable failures. Shingles on a 1:12 porch roof start leaking within a season or two as water wicks under tabs. Tile on a 3:12 main roof develops persistent leaks regardless of underlayment because water can travel backward under the profiles.</p>
<p>Adding square footage without upgrading drainage creates problems too. Tying a new flat addition into an old drain system sized for a smaller roof can overwhelm capacity during typical storms, leading to ponding and water intrusion.</p>
<p>Skipping tapered insulation on a nominally &ldquo;flat&rdquo; roof essentially guarantees ponding. These roofs need engineered slope in the assembly itself, not just membrane installed on flat decking.</p>
<p>Ventilation design also depends on pitch. Low-slope roofs may need powered ventilation rather than relying on soffit-and-ridge airflow that works well in steeper attic spaces.</p>
<p>When chronic pitch-related issues push a roof from repairable to replacement territory, understanding why helps you make a better decision. Our article on <a href="/blog/choosing-between-roof-repair-and-full-replacement">choosing between roof repair and full replacement</a> covers that call in more detail.</p>
<h2>Should You Change Your Roof Pitch During a Replacement?</h2>
<p>For most Broward and Palm Beach homes, dramatically changing roof pitch during a standard roof replacement is not practical or cost-effective.</p>
<p>Changing pitch typically means removing existing trusses or rafters, redesigning the roof structure, and obtaining engineer-stamped drawings and new permits. That is closer to major reconstruction than a re-roof.</p>
<p>There are valid exceptions: adding a new covered porch with its own pitch, building a substantial addition, or correcting a documented ponding problem with an engineered structural overlay. These projects justify the additional complexity.</p>
<p>Qualitatively, flat-to-sloped rebuilds often run two to three times the cost of a standard replacement because of the added framing, engineering, and finishing work. If you are even considering a pitch change, start with a professional <a href="/roof-inspection">roof inspection</a> so you know what is actually involved before budgeting. And if you also want context on how Palm Beach and Broward diverge on structural requirements, our guide on <a href="/blog/why-palm-beach-and-broward-county-building-codes-differ-a-south-florida-guide-by-all-phase-construction-usa">why Palm Beach and Broward building codes differ</a> is a useful companion.</p>
<h2>How All Phase Construction Approaches Roof Pitch Decisions</h2>
<p>We inspect pitch as part of every estimate, verifying existing slopes, evaluating drainage patterns, and checking for ponding or historical leak points before recommending a solution.</p>
<p>Our team confirms material compatibility with the actual measured pitch and local code requirements. We will not recommend tile for a 3:12 roof or shingles for a near-flat section — regardless of what a homeowner hopes to install — because the wrong material on the wrong pitch leaks.</p>
<p>Drainage is designed specifically for each roof&rsquo;s square footage, pitch, and layout. We do not apply generic templates that ignore your home&rsquo;s unique characteristics.</p>
<p>All Phase Construction is licensed as CCC-1331464 (Roofing Contractor) and CGC-1526236 (General Contractor) in Florida. We maintain a 4.8/5 rating from over 136 verified reviews — you can see what our customers say on our <a href="/south-florida-roofing-reviews">reviews page</a>.</p>
<h2>FAQ: Roof Pitch, Drainage, and South Florida Homes</h2>
<p><strong>What is the minimum roof pitch for shingles in Florida?</strong></p>
<p>Most modern architectural asphalt shingles are rated for a minimum slope of 2:12 as long as installers use enhanced underlayment — typically two layers or a peel-and-stick membrane — per manufacturer instructions. Below 2:12, code and manufacturers generally require membrane-type roofing systems because water will not shed quickly enough to prevent damage. If you are unsure of your actual pitch, schedule a professional measurement before buying materials.</p>
<p><strong>Can I install tile on a low-slope roof in South Florida?</strong></p>
<p>Most concrete and clay tile products used in Broward and Palm Beach require at least a 4:12 pitch, and some profiles call for 5:12 or steeper. Installing tile on too shallow a roof invites wicking leaks regardless of underlayment quality because water can travel backward under the tiles. Verify both your actual pitch and the specific tile manufacturer&rsquo;s minimum slope requirements before proceeding.</p>
<p><strong>Is my flat roof supposed to have standing water after it rains?</strong></p>
<p>A thin film immediately after a storm is normal, but noticeable ponding still present roughly 48 hours later indicates a problem. Likely causes include inadequate slope in the deck or tapered insulation, clogged drains or scuppers, or structural deflection in older framing. Catching these issues early is typically far less expensive than waiting for active leaks.</p>
<p><strong>Can I change my roof pitch during a regular roof replacement?</strong></p>
<p>Changing pitch significantly almost always requires new trusses or rafters, revised wall heights, and engineering — making it substantial reconstruction rather than a standard re-roof. Smaller localized changes, such as improving slope on a chronic ponding spot with tapered framing, are sometimes possible without rebuilding everything. Discuss your goals and budget with a licensed contractor through our <a href="/contact">contact page</a>.</p>
<p><strong>How does roof pitch affect my roof&rsquo;s hurricane performance rating?</strong></p>
<p>Pitch alone is not the main driver of hurricane performance. Fastening schedules, material wind ratings, and edge and penetration detailing have far more impact on how your roof handles high winds. Both flat and steep-slope roofs can achieve 150+ mph ratings when they are built with properly rated materials and installed to the Florida Building Code. Have your roof evaluated for wind performance as part of a broader inspection.</p>
<h2>Next Steps for South Florida Homeowners</h2>
<p>Roof pitch shapes how water drains, what materials you can safely use, and how your home performs in South Florida&rsquo;s intense climate. Understanding your current pitch — and its limitations — should inform any upcoming roof repair, replacement, or major remodel decision.</p>
<p>Broward and Palm Beach homeowners are welcome to schedule a professional <a href="/roof-inspection">roof inspection</a> or reach out through our <a href="/contact">contact page</a> to discuss specifics. With a 4.8/5 rating from over 136 verified reviews on our <a href="/south-florida-roofing-reviews">reviews page</a>, All Phase Construction has the local track record to guide you through these decisions.</p>
<p>Licensed CCC-1331464 (Roofing) and CGC-1526236 (General Contractor).</p>$BODY$
WHERE slug = 'the-role-of-roof-pitch-in-water-drainage-and-design';
