/**
 * City Project Photos Manifest (PR-73)
 *
 * Maps each city slug to an array of REAL project photos from
 * public/projects/. These are pulled into the city pages by the
 * CityProjectGallery component.
 *
 * Source: 212 webp project photos in public/projects/, filename-tagged
 * with city. 15 cities currently have project photos matched; 32 cities
 * are gaps awaiting field photos.
 *
 * Generated by PR-73 automation. Update by re-running the matcher script
 * when new city-tagged photos land in public/projects/.
 */

export interface CityProjectPhoto {
  file: string;     // basename in public/projects/
  alt: string;      // descriptive alt text
}

export const CITY_PROJECT_PHOTOS: Record<string, CityProjectPhoto[]> = {
  "boca-raton": [
    {
      "file": "all-phase-usa-metal-roof-replacement-boca-raton.webp",
      "alt": "Metal Roof Replacement Boca Raton \u2014 All Phase Construction USA"
    },
    {
      "file": "applying-swr-boca-raton-all-phase-usa.webp",
      "alt": "Applying Swr Boca Raton \u2014 All Phase Construction USA"
    }
  ],
  "davie": [
    {
      "file": "attic-inspection-in-davie-fl-found-leaks-not-detected-from-the-roof-all-phase-usa.webp",
      "alt": "Attic Inspection In Davie Fl Found Leaks Not Detected From The Roof \u2014 All Phase Construction USA"
    },
    {
      "file": "davie-attic-inspection-found-leak-all-phase-usa.webp",
      "alt": "Davie Attic Inspection Found Leak \u2014 All Phase Construction USA"
    }
  ],
  "boynton-beach": [
    {
      "file": "boynton-beach-backnailing-swr-all-phase-usa.webp",
      "alt": "Boynton Beach Backnailing Swr \u2014 All Phase Construction USA"
    },
    {
      "file": "boynton-beach-satisfied-customer-all-phase-usa.webp",
      "alt": "Boynton Beach Satisfied Customer \u2014 All Phase Construction USA"
    }
  ],
  "margate": [
    {
      "file": "cleaning-flat-roof-margate-fl-by-all-phase-usa.webp",
      "alt": "Cleaning Flat Roof Margate Fl By \u2014 All Phase Construction USA"
    },
    {
      "file": "flat-roof-cleaned-margate-fl-by-all-phase-usa.webp",
      "alt": "Flat Roof Cleaned Margate Fl By \u2014 All Phase Construction USA"
    }
  ],
  "coral-springs": [
    {
      "file": "coral-springs-barrel-tile-roof-replacement-all-phase-usa.webp",
      "alt": "Coral Springs Barrel Tile Roof Replacement \u2014 All Phase Construction USA"
    },
    {
      "file": "coral-springs-hvhz-tile-roof-inspection-all-phase-usa.webp",
      "alt": "Coral Springs Hvhz Tile Roof Inspection \u2014 All Phase Construction USA"
    }
  ],
  "west-palm-beach": [
    {
      "file": "coverboard-installed-over-insulation-board-for-flat-roof-in-west-palm-beach-fl.webp",
      "alt": "Coverboard Installed Over Insulation Board For Flat Roof In West Palm Beach Fl \u2014 All Phase Construction USA"
    },
    {
      "file": "flat-roof-replacement-in-progress-in-west-palm-beach-fl-by-all-phase-usa.webp",
      "alt": "Flat Roof Replacement In Progress In West Palm Beach Fl By \u2014 All Phase Construction USA"
    }
  ],
  "deerfield-beach": [
    {
      "file": "deerfield-beach-commercial-flat-roof-installed-by-all-phase-usa.webp",
      "alt": "Deerfield Beach Commercial Flat Roof Installed By \u2014 All Phase Construction USA"
    },
    {
      "file": "deerfield-beach-commercial-tile-roof-all-phase-usa.webp",
      "alt": "Deerfield Beach Commercial Tile Roof \u2014 All Phase Construction USA"
    }
  ],
  "delray-beach": [
    {
      "file": "delray-beach-drip-edge-install-all-phase-usa.webp",
      "alt": "Delray Beach Drip Edge Install \u2014 All Phase Construction USA"
    },
    {
      "file": "delray-beach-roof-in-progress-all-phase-usa.webp",
      "alt": "Delray Beach Roof In Progress \u2014 All Phase Construction USA"
    }
  ],
  "tamarac": [
    {
      "file": "detailed-roof-repair-tamarac-all-phase-usa.webp",
      "alt": "Detailed Roof Repair Tamarac \u2014 All Phase Construction USA"
    },
    {
      "file": "roof-repair-transition-where-slope-meets-flat-roof-tamarac-fl-all-phase-usa.webp",
      "alt": "Roof Repair Transition Where Slope Meets Flat Roof Tamarac Fl \u2014 All Phase Construction USA"
    }
  ],
  "fort-lauderdale": [
    {
      "file": "fort-lauderdale-metal-roof-in-progress-all-phase-usa.webp",
      "alt": "Fort Lauderdale Metal Roof In Progress \u2014 All Phase Construction USA"
    },
    {
      "file": "fort-lauderdale-metal-roof-replacement-all-phase-usa.webp",
      "alt": "Fort Lauderdale Metal Roof Replacement \u2014 All Phase Construction USA"
    }
  ],
  "pembroke-pines": [
    {
      "file": "new-roof-coming-soon-pembroke-pines-all-phase-usa.webp",
      "alt": "New Roof Coming Soon Pembroke Pines \u2014 All Phase Construction USA"
    }
  ],
  "palm-beach": [
    {
      "file": "palm-beach-flat-roof-replacement-all-phase-usa.webp",
      "alt": "Palm Beach Flat Roof Replacement \u2014 All Phase Construction USA"
    },
    {
      "file": "palm-beach-flat-roof-single-ply-installation-all-phase-usa.webp",
      "alt": "Palm Beach Flat Roof Single Ply Installation \u2014 All Phase Construction USA"
    }
  ],
  "pompano-beach": [
    {
      "file": "pompano-beach-commercial-flat-roof-all-phase-usa.webp",
      "alt": "Pompano Beach Commercial Flat Roof \u2014 All Phase Construction USA"
    },
    {
      "file": "pompano-beach-commercial-flat-roof-inspection-all-phase-usa.webp",
      "alt": "Pompano Beach Commercial Flat Roof Inspection \u2014 All Phase Construction USA"
    }
  ],
  "wellington": [
    {
      "file": "roof-repair-wellington-all-phase-usa.webp",
      "alt": "Roof Repair Wellington \u2014 All Phase Construction USA"
    },
    {
      "file": "tile-roof-repair-in-progress-wellington-all-phase-usa.webp",
      "alt": "Tile Roof Repair In Progress Wellington \u2014 All Phase Construction USA"
    }
  ],
  "sunrise": [
    {
      "file": "shingle-roof-and-flat-roof-replacement-inspection-sunrise-fl-all-phase-usa.webp",
      "alt": "Shingle Roof And Flat Roof Replacement Inspection Sunrise Fl \u2014 All Phase Construction USA"
    },
    {
      "file": "sunrise-fl-shingle-roof-replacement-all-phase-usa.webp",
      "alt": "Sunrise Fl Shingle Roof Replacement \u2014 All Phase Construction USA"
    }
  ]
};
