/**
 * getCityEnrichment — Single source of truth for city-specific data
 * used by the GenericRoofInspectionTemplate and GenericRoofRepairTemplate
 * to break the thin-content pattern flagged by Google's crawled-not-indexed
 * filter (228 URLs documented in PR-86 investigation).
 *
 * Priority:
 *   1. src/data/locations.ts (richest data — neighborhoods, ZIPs, landmarks,
 *      localHook). Used for the 31 cities with money-page representation.
 *   2. src/data/cities.json (minimal — just slug/city/county) as fallback.
 *
 * Returns null when slug is unknown (template will degrade gracefully).
 */
import cities from './cities.json';

// We parse locations.ts at runtime via a generated lookup. The file is
// regenerated by scripts/build-location-enrichment.mjs at build time.
// For now we duck-type the import inline.
//
// NOTE: a runtime parse of locations.ts would require a TS->JSON build
// step. For PR-90 we keep the lookup as a hand-maintained object covering
// the cities currently in the crawled-not-indexed bucket plus the ones
// already enriched in locations.ts. This is the most surgical fix.

export interface CityEnrichment {
  slug: string;
  city: string;
  county: string;
  hvhz: boolean;
  neighborhoods?: string[];
  zips?: string[];
  landmarks?: string[];
  localHook?: string;
}

// PR-90 enrichment data. Mirrors the relevant fields from
// src/data/locations.ts and supplements with cities that need
// content uniqueness to escape Google's thin-content filter.
const ENRICHMENT: Record<string, Omit<CityEnrichment, 'slug'>> = {
  'boca-raton': {
    city: 'Boca Raton', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Boca West', 'The Oaks at Boca Raton', 'Royal Palm Yacht & Country Club', 'Mizner Park', 'Boca Pointe', 'Camino Gardens'],
    zips: ['33427', '33428', '33429', '33431', '33432', '33433', '33434', '33486', '33487', '33488', '33496', '33497', '33498'],
    landmarks: ['Mizner Park', 'Florida Atlantic University', 'Spanish River Park', 'Boca Raton Resort & Club'],
    localHook: 'Boca Raton Building Department generally prefers Miami-Dade HVHZ standards even though the city is non-HVHZ. We voluntarily install every Boca roof to that spec for maximum wind protection.',
  },
  'boynton-beach': {
    city: 'Boynton Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Hunters Run', 'Quail Ridge', 'Indian Spring', 'Aberdeen', 'Valencia Reserve', '55+ communities west of Jog Road'],
    zips: ['33426', '33435', '33436', '33437', '33472', '33473', '33474'],
    landmarks: ['Boynton Beach Inlet', 'Boynton Beach Marina', 'Bethesda Hospital East'],
    localHook: 'Boynton Beach has a heavy 55+ community concentration west of Jog Road. We work the HOA architectural-review process and re-roof these communities to Miami-Dade HVHZ spec for insurance and wind protection.',
  },
  'coral-springs': {
    city: 'Coral Springs', county: 'Broward', hvhz: true,
    neighborhoods: ['Eagle Trace', 'Whispering Woods', 'Heron Bay', 'Pine Ridge', 'Forest Hills', 'Ramblewood'],
    zips: ['33065', '33067', '33071', '33073', '33076'],
    landmarks: ['Sawgrass Expressway corridor', 'Sample Road', 'University Drive', 'Coral Springs Center for the Arts'],
    localHook: 'Coral Springs has a HVHZ-mandated permitting workflow at the city building department on Coral Springs Drive. Our crews know the inspection sequence and the typical truss profiles in the late-1970s and 1980s housing stock.',
  },
  'davie': {
    city: 'Davie', county: 'Broward', hvhz: true,
    neighborhoods: ['Long Lake Ranches', 'Forest Ridge', 'Ivanhoe', 'Bonaventure', 'Pine Island Ridge', 'Stonebrook'],
    zips: ['33024', '33312', '33314', '33317', '33324', '33325', '33326', '33328', '33329', '33330', '33331'],
    landmarks: ['Nova Southeastern University', 'Bergeron Rodeo Grounds', 'Robbins Park'],
    localHook: 'Davie housing stock spans from acreage ranch homes off Stirling Road to dense townhouse villages near Nova Southeastern. We carry the dual license to handle structural decking and rafter conditions common in older Davie roof tear-offs.',
  },
  'delray-beach': {
    city: 'Delray Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Mizner Country Club', 'Polo Trace', 'The Hamlet', 'Bocaire', 'Banyan Tree Estates', 'Tropic Isles'],
    zips: ['33444', '33445', '33446', '33483', '33484'],
    landmarks: ['Atlantic Avenue', 'Delray Beach Marina', 'Old School Square', 'Morikami Museum'],
    localHook: 'Delray Beach housing stock ranges from waterfront Tropic Isles to inland country club communities west of Military Trail. We install voluntarily to Miami-Dade HVHZ spec for insurance discount eligibility.',
  },
  'fort-lauderdale': {
    city: 'Fort Lauderdale', county: 'Broward', hvhz: true,
    neighborhoods: ['Las Olas Isles', 'Coral Ridge', 'Rio Vista', 'Victoria Park', 'Lauderdale Harbours', 'Imperial Point'],
    zips: ['33301', '33304', '33305', '33306', '33308', '33309', '33311', '33312', '33315', '33316', '33334'],
    landmarks: ['Las Olas Boulevard', 'Port Everglades', 'Fort Lauderdale Beach', 'New River'],
    localHook: 'Fort Lauderdale spans waterfront mansions on the New River Isles to mid-century homes in Coral Ridge. Direct ocean exposure makes HVHZ-spec installation with reinforced ridge attachment non-negotiable on every Fort Lauderdale roof.',
  },
  'hallandale-beach': {
    city: 'Hallandale Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Hallandale Beach high-rises', 'Three Islands', 'Layne Boulevard area', 'Diplomat Country Club'],
    zips: ['33008', '33009'],
    landmarks: ['Hallandale Beach Boulevard', 'Gulfstream Park', 'Diplomat Country Club'],
    localHook: 'Hallandale Beach skews to dense condos and townhouses with flat and low-slope roofs. We carry the commercial-grade single-ply experience these properties require alongside steep-slope residential.',
  },
  'hollywood': {
    city: 'Hollywood', county: 'Broward', hvhz: true,
    neighborhoods: ['Emerald Hills', 'Hollywood Hills', 'Highland Gardens', 'Hollywood Lakes', 'Park East', 'Driftwood'],
    zips: ['33019', '33020', '33021', '33023', '33024', '33025', '33026', '33027', '33028', '33029'],
    landmarks: ['Hollywood Boardwalk', 'Hollywood Beach', 'Seminole Hard Rock Hotel', 'Anne Kolb Nature Center'],
    localHook: 'Hollywood combines beachfront condos with established inland neighborhoods like Emerald Hills and Hollywood Hills. Salt-air corrosion on metal fasteners drives our use of stainless ring-shank nails on every Hollywood install east of Federal Highway.',
  },
  'miramar': {
    city: 'Miramar', county: 'Broward', hvhz: true,
    neighborhoods: ['Sunset Lakes', 'Silver Lakes', 'Riviera Isles', 'Vizcaya', 'Avalon', 'Huntington'],
    zips: ['33023', '33025', '33027', '33029'],
    landmarks: ['Miramar Cultural Center', 'Vista Park', 'Pembroke Road corridor'],
    localHook: 'Miramar housing is dominated by 1990s and 2000s tract construction with original shingle roofs now reaching end-of-service-life. We re-roof Miramar at scale, with crews familiar with the HOA architectural review processes in Sunset Lakes and Silver Lakes.',
  },
  'parkland': {
    city: 'Parkland', county: 'Broward', hvhz: true,
    neighborhoods: ['Heron Bay', 'Pine Tree Estates', 'Country Place', 'Cypress Cay', 'Mayfair', 'Cascata'],
    zips: ['33067', '33076'],
    landmarks: ['Pine Trails Park', 'Marjory Stoneman Douglas High', 'Parkland Equestrian Center'],
    localHook: 'Parkland is dominated by 5,000+ sq ft estate homes in gated communities like Heron Bay and Cascata. Tile and slate-style metal roofs dominate; we carry the HOA architectural-review experience that gets a Parkland tile reroof approved in days, not weeks.',
  },
  'pembroke-pines': {
    city: 'Pembroke Pines', county: 'Broward', hvhz: true,
    neighborhoods: ['Pembroke Falls', 'Spring Valley', 'Chapel Trail', 'Walnut Creek', 'Pembroke Shores', 'Century Village'],
    zips: ['33023', '33024', '33025', '33026', '33027', '33028', '33029', '33082'],
    landmarks: ['Pembroke Lakes Mall', 'C.B. Smith Park', 'Pines Boulevard corridor'],
    localHook: 'Pembroke Pines has substantial 55+ Century Village inventory plus established family neighborhoods like Pembroke Falls. We re-roof both ends — the HOA-coordinated 55+ buildings and the single-family stock — to HVHZ spec.',
  },
  'plantation': {
    city: 'Plantation', county: 'Broward', hvhz: true,
    neighborhoods: ['Plantation Acres', 'Hawks Landing', 'Plantation Park', 'Jacaranda Lakes', 'Lauderdale West', 'Sunset Square'],
    zips: ['33313', '33317', '33322', '33323', '33324', '33325', '33388'],
    landmarks: ['Broward Mall', 'Plantation Heritage Park', 'Plantation Preserve Golf Course'],
    localHook: 'Plantation neighborhoods range from horse-property acreage in Plantation Acres to dense townhouse villages off University Drive. We work the city building department on NW 70th Avenue and know the typical sequencing of HVHZ inspections in Plantation.',
  },
  'pompano-beach': {
    city: 'Pompano Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Cypress Lakes', 'Palm Aire', 'Harbor Village', 'Crystal Lake', 'Pompano Beach Highlands', 'Cresthaven'],
    zips: ['33060', '33061', '33062', '33063', '33064', '33065', '33066', '33067', '33068', '33069', '33072', '33073', '33074', '33075', '33076', '33077', '33093', '33097'],
    landmarks: ['Pompano Beach Pier', 'Pompano Beach Air Park', 'Sample-McDougald House'],
    localHook: 'Pompano Beach spans waterfront homes east of Federal Highway to inland 55+ Palm Aire and Cypress Lakes communities. We carry the marine-grade fastener and salt-air ridge-detail experience that Pompano oceanfront roofs require.',
  },
  'sunrise': {
    city: 'Sunrise', county: 'Broward', hvhz: true,
    neighborhoods: ['Sawgrass', 'Welleby', 'Sunrise Lakes', 'Springtree', 'Sunrise Golf Village'],
    zips: ['33304', '33313', '33319', '33322', '33323', '33325', '33326', '33345', '33351'],
    landmarks: ['BB&T Center', 'Sawgrass Mills', 'Markham Park'],
    localHook: 'Sunrise blends 55+ Sunrise Lakes towers and mid-rises with single-family neighborhoods like Welleby and Sawgrass. We re-roof both at scale, handling both flat single-ply on the towers and steep-slope tile/shingle on the single-family stock.',
  },
  'wellington': {
    city: 'Wellington', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Palm Beach Polo', 'Wellington Trace', 'Mayacoo Lakes', 'Olympia', 'The Landings', 'Equestrian Club'],
    zips: ['33414', '33449'],
    landmarks: ['International Polo Club', 'Wellington Equestrian Preserve', 'Mall at Wellington Green'],
    localHook: 'Wellington equestrian estates and country club communities require concrete tile, clay tile, and standing-seam metal installations engineered for direct exposure and HOA architectural review. We voluntarily install to Miami-Dade HVHZ spec.',
  },
  'jupiter': {
    city: 'Jupiter', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Admirals Cove', 'Jonathan’s Landing', 'Jupiter Inlet Colony', 'Tequesta border', 'Abacoa', 'Maplewood'],
    zips: ['33458', '33468', '33469', '33477', '33478'],
    landmarks: ['Jupiter Lighthouse', 'Jupiter Beach', 'Roger Dean Stadium'],
    localHook: 'Jupiter waterfront homes on the Intracoastal and the Loxahatchee River face direct Atlantic wind exposure. Our Jupiter tile and metal installs go in to Miami-Dade HVHZ spec with reinforced ridge attachment for maximum coastal longevity.',
  },
  'palm-beach-gardens': {
    city: 'Palm Beach Gardens', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['BallenIsles', 'Frenchmans Reserve', 'PGA National', 'Mirasol', 'Old Marsh', 'Eastpointe'],
    zips: ['33403', '33408', '33410', '33412', '33418'],
    landmarks: ['Gardens Mall', 'PGA Boulevard corridor', 'PGA National Resort'],
    localHook: 'Palm Beach Gardens country club communities like PGA National and BallenIsles require coordinated HOA architectural review for any re-roof. We carry the documentation pipeline that gets a Palm Beach Gardens tile or metal project approved cleanly.',
  },
};

// Also pull from cities.json for cities not in ENRICHMENT
const CITIES_FALLBACK: Record<string, { city: string }> = {};
for (const c of cities as Array<{ slug: string; city: string }>) {
  CITIES_FALLBACK[c.slug] = { city: c.city };
}

export function getCityEnrichment(slug: string): CityEnrichment | null {
  const data = ENRICHMENT[slug];
  if (data) {
    return { slug, ...data };
  }
  const fallback = CITIES_FALLBACK[slug];
  if (fallback) {
    return {
      slug,
      city: fallback.city,
      county: 'South Florida',
      hvhz: false,
    };
  }
  return null;
}
