/**
 * getCityEnrichment — Single source of truth for city-specific data
 * used by the GenericRoofInspectionTemplate and GenericRoofRepairTemplate
 * to break the thin-content pattern flagged by Google's crawled-not-indexed
 * filter (228 URLs documented in PR-86 investigation).
 *
 * Priority:
 *   1. src/data/locations.ts (richest data — neighborhoods, ZIPs, landmarks,
 *      localHook). Used for the 31 cities with money-page representation.
 *   2. src/data/cities.json (minimal — just slug/city/county) as fallback.
 *
 * Returns null when slug is unknown (template will degrade gracefully).
 */
import cities from './cities.json';

// We parse locations.ts at runtime via a generated lookup. The file is
// regenerated by scripts/build-location-enrichment.mjs at build time.
// For now we duck-type the import inline.
//
// NOTE: a runtime parse of locations.ts would require a TS->JSON build
// step. For PR-90 we keep the lookup as a hand-maintained object covering
// the cities currently in the crawled-not-indexed bucket plus the ones
// already enriched in locations.ts. This is the most surgical fix.

export interface CityEnrichment {
  slug: string;
  city: string;
  county: string;
  hvhz: boolean;
  neighborhoods?: string[];
  zips?: string[];
  landmarks?: string[];
  localHook?: string;
}

// PR-90 enrichment data. Mirrors the relevant fields from
// src/data/locations.ts and supplements with cities that need
// content uniqueness to escape Google's thin-content filter.
const ENRICHMENT: Record<string, Omit<CityEnrichment, 'slug'>> = {
  'boca-raton': {
    city: 'Boca Raton', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Boca West', 'The Oaks at Boca Raton', 'Royal Palm Yacht & Country Club', 'Mizner Park', 'Boca Pointe', 'Camino Gardens'],
    zips: ['33427', '33428', '33429', '33431', '33432', '33433', '33434', '33486', '33487', '33488', '33496', '33497', '33498'],
    landmarks: ['Mizner Park', 'Florida Atlantic University', 'Spanish River Park', 'Boca Raton Resort & Club'],
    localHook: 'Boca Raton Building Department generally prefers Miami-Dade HVHZ standards even though the city is non-HVHZ. We voluntarily install every Boca roof to that spec for maximum wind protection.',
  },
  'boynton-beach': {
    city: 'Boynton Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Hunters Run', 'Quail Ridge', 'Indian Spring', 'Aberdeen', 'Valencia Reserve', '55+ communities west of Jog Road'],
    zips: ['33426', '33435', '33436', '33437', '33472', '33473', '33474'],
    landmarks: ['Boynton Beach Inlet', 'Boynton Beach Marina', 'Bethesda Hospital East'],
    localHook: 'Boynton Beach has a heavy 55+ community concentration west of Jog Road. We work the HOA architectural-review process and re-roof these communities to Miami-Dade HVHZ spec for insurance and wind protection.',
  },
  'coral-springs': {
    city: 'Coral Springs', county: 'Broward', hvhz: true,
    neighborhoods: ['Eagle Trace', 'Whispering Woods', 'Heron Bay', 'Pine Ridge', 'Forest Hills', 'Ramblewood'],
    zips: ['33065', '33067', '33071', '33073', '33076'],
    landmarks: ['Sawgrass Expressway corridor', 'Sample Road', 'University Drive', 'Coral Springs Center for the Arts'],
    localHook: 'Coral Springs has a HVHZ-mandated permitting workflow at the city building department on Coral Springs Drive. Our crews know the inspection sequence and the typical truss profiles in the late-1970s and 1980s housing stock.',
  },
  'davie': {
    city: 'Davie', county: 'Broward', hvhz: true,
    neighborhoods: ['Long Lake Ranches', 'Forest Ridge', 'Ivanhoe', 'Bonaventure', 'Pine Island Ridge', 'Stonebrook'],
    zips: ['33024', '33312', '33314', '33317', '33324', '33325', '33326', '33328', '33329', '33330', '33331'],
    landmarks: ['Nova Southeastern University', 'Bergeron Rodeo Grounds', 'Robbins Park'],
    localHook: 'Davie housing stock spans from acreage ranch homes off Stirling Road to dense townhouse villages near Nova Southeastern. We carry the dual license to handle structural decking and rafter conditions common in older Davie roof tear-offs.',
  },
  'delray-beach': {
    city: 'Delray Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Mizner Country Club', 'Polo Trace', 'The Hamlet', 'Bocaire', 'Banyan Tree Estates', 'Tropic Isles'],
    zips: ['33444', '33445', '33446', '33483', '33484'],
    landmarks: ['Atlantic Avenue', 'Delray Beach Marina', 'Old School Square', 'Morikami Museum'],
    localHook: 'Delray Beach housing stock ranges from waterfront Tropic Isles to inland country club communities west of Military Trail. We install voluntarily to Miami-Dade HVHZ spec for insurance discount eligibility.',
  },
  'fort-lauderdale': {
    city: 'Fort Lauderdale', county: 'Broward', hvhz: true,
    neighborhoods: ['Las Olas Isles', 'Coral Ridge', 'Rio Vista', 'Victoria Park', 'Lauderdale Harbours', 'Imperial Point'],
    zips: ['33301', '33304', '33305', '33306', '33308', '33309', '33311', '33312', '33315', '33316', '33334'],
    landmarks: ['Las Olas Boulevard', 'Port Everglades', 'Fort Lauderdale Beach', 'New River'],
    localHook: 'Fort Lauderdale spans waterfront mansions on the New River Isles to mid-century homes in Coral Ridge. Direct ocean exposure makes HVHZ-spec installation with reinforced ridge attachment non-negotiable on every Fort Lauderdale roof.',
  },
  'hallandale-beach': {
    city: 'Hallandale Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Hallandale Beach high-rises', 'Three Islands', 'Layne Boulevard area', 'Diplomat Country Club'],
    zips: ['33008', '33009'],
    landmarks: ['Hallandale Beach Boulevard', 'Gulfstream Park', 'Diplomat Country Club'],
    localHook: 'Hallandale Beach skews to dense condos and townhouses with flat and low-slope roofs. We carry the commercial-grade single-ply experience these properties require alongside steep-slope residential.',
  },
  'hollywood': {
    city: 'Hollywood', county: 'Broward', hvhz: true,
    neighborhoods: ['Emerald Hills', 'Hollywood Hills', 'Highland Gardens', 'Hollywood Lakes', 'Park East', 'Driftwood'],
    zips: ['33019', '33020', '33021', '33023', '33024', '33025', '33026', '33027', '33028', '33029'],
    landmarks: ['Hollywood Boardwalk', 'Hollywood Beach', 'Seminole Hard Rock Hotel', 'Anne Kolb Nature Center'],
    localHook: 'Hollywood combines beachfront condos with established inland neighborhoods like Emerald Hills and Hollywood Hills. Salt-air corrosion on metal fasteners drives our use of stainless ring-shank nails on every Hollywood install east of Federal Highway.',
  },
  'miramar': {
    city: 'Miramar', county: 'Broward', hvhz: true,
    neighborhoods: ['Sunset Lakes', 'Silver Lakes', 'Riviera Isles', 'Vizcaya', 'Avalon', 'Huntington'],
    zips: ['33023', '33025', '33027', '33029'],
    landmarks: ['Miramar Cultural Center', 'Vista Park', 'Pembroke Road corridor'],
    localHook: 'Miramar housing is dominated by 1990s and 2000s tract construction with original shingle roofs now reaching end-of-service-life. We re-roof Miramar at scale, with crews familiar with the HOA architectural review processes in Sunset Lakes and Silver Lakes.',
  },
  'parkland': {
    city: 'Parkland', county: 'Broward', hvhz: true,
    neighborhoods: ['Heron Bay', 'Pine Tree Estates', 'Country Place', 'Cypress Cay', 'Mayfair', 'Cascata'],
    zips: ['33067', '33076'],
    landmarks: ['Pine Trails Park', 'Marjory Stoneman Douglas High', 'Parkland Equestrian Center'],
    localHook: 'Parkland is dominated by 5,000+ sq ft estate homes in gated communities like Heron Bay and Cascata. Tile and slate-style metal roofs dominate; we carry the HOA architectural-review experience that gets a Parkland tile reroof approved in days, not weeks.',
  },
  'pembroke-pines': {
    city: 'Pembroke Pines', county: 'Broward', hvhz: true,
    neighborhoods: ['Pembroke Falls', 'Spring Valley', 'Chapel Trail', 'Walnut Creek', 'Pembroke Shores', 'Century Village'],
    zips: ['33023', '33024', '33025', '33026', '33027', '33028', '33029', '33082'],
    landmarks: ['Pembroke Lakes Mall', 'C.B. Smith Park', 'Pines Boulevard corridor'],
    localHook: 'Pembroke Pines has substantial 55+ Century Village inventory plus established family neighborhoods like Pembroke Falls. We re-roof both ends — the HOA-coordinated 55+ buildings and the single-family stock — to HVHZ spec.',
  },
  'plantation': {
    city: 'Plantation', county: 'Broward', hvhz: true,
    neighborhoods: ['Plantation Acres', 'Hawks Landing', 'Plantation Park', 'Jacaranda Lakes', 'Lauderdale West', 'Sunset Square'],
    zips: ['33313', '33317', '33322', '33323', '33324', '33325', '33388'],
    landmarks: ['Broward Mall', 'Plantation Heritage Park', 'Plantation Preserve Golf Course'],
    localHook: 'Plantation neighborhoods range from horse-property acreage in Plantation Acres to dense townhouse villages off University Drive. We work the city building department on NW 70th Avenue and know the typical sequencing of HVHZ inspections in Plantation.',
  },
  'pompano-beach': {
    city: 'Pompano Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Cypress Lakes', 'Palm Aire', 'Harbor Village', 'Crystal Lake', 'Pompano Beach Highlands', 'Cresthaven'],
    zips: ['33060', '33061', '33062', '33063', '33064', '33065', '33066', '33067', '33068', '33069', '33072', '33073', '33074', '33075', '33076', '33077', '33093', '33097'],
    landmarks: ['Pompano Beach Pier', 'Pompano Beach Air Park', 'Sample-McDougald House'],
    localHook: 'Pompano Beach spans waterfront homes east of Federal Highway to inland 55+ Palm Aire and Cypress Lakes communities. We carry the marine-grade fastener and salt-air ridge-detail experience that Pompano oceanfront roofs require.',
  },
  'sunrise': {
    city: 'Sunrise', county: 'Broward', hvhz: true,
    neighborhoods: ['Sawgrass', 'Welleby', 'Sunrise Lakes', 'Springtree', 'Sunrise Golf Village'],
    zips: ['33304', '33313', '33319', '33322', '33323', '33325', '33326', '33345', '33351'],
    landmarks: ['BB&T Center', 'Sawgrass Mills', 'Markham Park'],
    localHook: 'Sunrise blends 55+ Sunrise Lakes towers and mid-rises with single-family neighborhoods like Welleby and Sawgrass. We re-roof both at scale, handling both flat single-ply on the towers and steep-slope tile/shingle on the single-family stock.',
  },
  'wellington': {
    city: 'Wellington', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Palm Beach Polo', 'Wellington Trace', 'Mayacoo Lakes', 'Olympia', 'The Landings', 'Equestrian Club'],
    zips: ['33414', '33449'],
    landmarks: ['International Polo Club', 'Wellington Equestrian Preserve', 'Mall at Wellington Green'],
    localHook: 'Wellington equestrian estates and country club communities require concrete tile, clay tile, and standing-seam metal installations engineered for direct exposure and HOA architectural review. We voluntarily install to Miami-Dade HVHZ spec.',
  },
  'jupiter': {
    city: 'Jupiter', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Admirals Cove', 'Jonathan’s Landing', 'Jupiter Inlet Colony', 'Tequesta border', 'Abacoa', 'Maplewood'],
    zips: ['33458', '33468', '33469', '33477', '33478'],
    landmarks: ['Jupiter Lighthouse', 'Jupiter Beach', 'Roger Dean Stadium'],
    localHook: 'Jupiter waterfront homes on the Intracoastal and the Loxahatchee River face direct Atlantic wind exposure. Our Jupiter tile and metal installs go in to Miami-Dade HVHZ spec with reinforced ridge attachment for maximum coastal longevity.',
  },
  'palm-beach-gardens': {
    city: 'Palm Beach Gardens', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['BallenIsles', 'Frenchmans Reserve', 'PGA National', 'Mirasol', 'Old Marsh', 'Eastpointe'],
    zips: ['33403', '33408', '33410', '33412', '33418'],
    landmarks: ['Gardens Mall', 'PGA Boulevard corridor', 'PGA National Resort'],
    localHook: 'Palm Beach Gardens country club communities like PGA National and BallenIsles require coordinated HOA architectural review for any re-roof. We carry the documentation pipeline that gets a Palm Beach Gardens tile or metal project approved cleanly.',
  },
  'coconut-creek': {
    city: 'Coconut Creek', county: 'Broward', hvhz: true,
    neighborhoods: ['Wynmoor Village', 'Township', 'Regency Lakes', 'Centura Parc', 'Cocobay'],
    zips: ['33063', '33066', '33073', '33076', '33093', '33097'],
    landmarks: ['Sample Road corridor', 'Tradewinds Park', 'Promenade at Coconut Creek'],
    localHook: 'Coconut Creek has a heavy concentration of 55+ condo and villa communities like Wynmoor that re-roof on board-coordinated cycles. We work the HOA architectural-review process and re-roof the buildings to HVHZ spec on a unified schedule.',
  },
  'cooper-city': {
    city: 'Cooper City', county: 'Broward', hvhz: true,
    neighborhoods: ['Embassy Lakes', 'Rock Creek', 'Monterra', 'Country Glen', 'Forest Lake'],
    zips: ['33024', '33026', '33328', '33330', '33331'],
    landmarks: ['Pioneer Middle School corridor', 'Cooper City High School', 'Stirling Road'],
    localHook: 'Cooper City has consistently been rated one of the top family-friendly cities in Broward. Housing stock is dominated by late-1980s and 1990s tract construction now reaching original-roof end-of-life. We re-roof these neighborhoods at scale.',
  },
  'dania-beach': {
    city: 'Dania Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Harbour Towne Marina area', 'Melaleuca Gardens', 'Estates of Fort Lauderdale', 'College Gardens'],
    zips: ['33004', '33312', '33316'],
    landmarks: ['Fort Lauderdale-Hollywood International Airport', 'Dania Beach Pier', 'Mardi Gras Casino'],
    localHook: 'Dania Beach has direct airport-adjacent flight-path housing with extra wind and noise exposure. We use reinforced underlayment and acoustic-rated decking detail on Dania re-roofs to handle both.',
  },
  'deerfield-beach': {
    city: 'Deerfield Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['The Cove', 'Deer Creek', 'Century Village', 'The Lakes', 'Crystal Lake', 'Waterford', 'Independence Bay'],
    zips: ['33064', '33441', '33442', '33443'],
    landmarks: ['Deerfield Beach Pier', 'Quiet Waters Park', 'Hillsboro Inlet', 'Sample Road corridor'],
    localHook: 'Deerfield Beach is All Phase Construction USA HQ since 2006. Every truck rolls from 590 Goolsby Boulevard. We know the city building department, the typical Century Village re-roof cycle, and the waterfront salt-air detail for The Cove.',
  },
  'greenacres': {
    city: 'Greenacres', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['River Bridge', 'Pinewood Manor', 'Maplewood', 'Eagle Pointe', 'Sherwood Forest'],
    zips: ['33413', '33415', '33463', '33467'],
    landmarks: ['Greenacres City Hall', 'John Prince Park', 'Lake Worth Drainage District E-3 canal'],
    localHook: 'Greenacres has substantial 1980s and 1990s single-family inventory now hitting original-roof end-of-life. We voluntarily install to Miami-Dade HVHZ spec across Greenacres for insurance-discount eligibility.',
  },
  'gulf-stream': {
    city: 'Gulf Stream', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Place Au Soleil', 'Gulf Stream Yacht Club', 'Pelican Lane'],
    zips: ['33483'],
    landmarks: ['Gulf Stream Golf Club', 'A1A corridor', 'Hillsboro Inlet'],
    localHook: 'Gulf Stream is a tiny ultra-affluent waterfront enclave between Delray Beach and Boynton Beach. Roof market skews to barrel-tile and standing-seam metal on estate-quality homes. We install to HVHZ spec with hand-selected NOA tile sourcing.',
  },
  'haverhill': {
    city: 'Haverhill', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Lakeshore Manor', 'Haverhill Village'],
    zips: ['33417'],
    landmarks: ['Haverhill Road corridor', 'Belvedere Road'],
    localHook: 'Haverhill is a small inland Palm Beach municipality with established 1970s and 1980s single-family stock. We re-roof these neighborhoods voluntarily to Miami-Dade HVHZ spec for full insurance-discount eligibility.',
  },
  'highland-beach': {
    city: 'Highland Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Bel Lido Isle', 'Boca Highlands', 'Toscana', 'Carlton House', 'Penthouse Towers'],
    zips: ['33487'],
    landmarks: ['Highland Beach Town Hall', 'A1A oceanfront corridor', 'Spanish River Park'],
    localHook: 'Highland Beach is the thin oceanfront barrier-island strip between Delray Beach and Boca Raton. Direct Atlantic exposure makes HVHZ-spec ridge attachment and salt-air-resistant fastening detail non-negotiable on every re-roof.',
  },
  'hillsboro-beach': {
    city: 'Hillsboro Beach', county: 'Broward', hvhz: true,
    neighborhoods: ['Hillsboro Mile estates', 'Sea Ranch Club', 'Hidden Harbour'],
    zips: ['33062'],
    landmarks: ['Hillsboro Lighthouse', 'Hillsboro Mile (A1A)', 'Hillsboro Inlet'],
    localHook: 'Hillsboro Beach is a tiny ultra-affluent barrier-island town with some of the highest property values in Broward. Direct Atlantic wind exposure plus salt air drives our use of marine-grade stainless fasteners and double-layer NOA underlayment on Hillsboro tile re-roofs.',
  },
  'hypoluxo': {
    city: 'Hypoluxo', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Hypoluxo Island', 'Manalapan border', 'Cassandra Lane'],
    zips: ['33462'],
    landmarks: ['Hypoluxo Road corridor', 'Intracoastal Waterway access'],
    localHook: 'Hypoluxo is a small waterfront village between Lantana and Manalapan with direct Intracoastal exposure. Wind and salt-air conditions match Boynton Beach proper — we install voluntarily to HVHZ spec for every Hypoluxo re-roof.',
  },
  'jupiter-inlet-colony': {
    city: 'Jupiter Inlet Colony', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Jupiter Inlet Colony (the whole village is one neighborhood)'],
    zips: ['33469'],
    landmarks: ['Jupiter Inlet Lighthouse', 'A1A waterfront'],
    localHook: 'Jupiter Inlet Colony is a tiny private waterfront village at the very tip of Jupiter. Roof market is exclusively high-end Spanish tile and standing-seam metal. We install to HVHZ spec with reinforced ridge attachment for direct ocean exposure.',
  },
  'lake-park': {
    city: 'Lake Park', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Lake Park Harbor', 'Maryland Avenue area', 'Park Avenue corridor'],
    zips: ['33403'],
    landmarks: ['Lake Park Marina', 'Old Dixie Highway', 'Park Avenue downtown'],
    localHook: 'Lake Park has a mix of older 1950s waterfront cottages and newer townhome developments. We handle both ends — period-correct detail on the older homes and modern HVHZ-spec installation on the newer stock.',
  },
  'lake-worth-beach': {
    city: 'Lake Worth Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Bryant Park', 'Parrot Cove', 'College Park', 'Tropical Ridge', 'South Palm Park'],
    zips: ['33460', '33461', '33462', '33463', '33467'],
    landmarks: ['Lake Worth Casino & Beach Complex', 'Snook Islands Natural Area', 'Lake Worth Pier'],
    localHook: 'Lake Worth Beach is a coastal city with a heavy concentration of pre-1960 cottage stock — original tongue-and-groove decking, dimensional framing, and roof systems at end-of-life. We carry the dual license to handle structural conditions common in older Lake Worth Beach tear-offs.',
  },
  'lantana': {
    city: 'Lantana', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Hypoluxo Island border', 'East Lantana', 'Lantana Beach'],
    zips: ['33462', '33465'],
    landmarks: ['Lantana Beach', 'Hypoluxo Road corridor', 'Lantana Marina'],
    localHook: 'Lantana has a mix of waterfront homes east of Federal Highway and inland family neighborhoods west of I-95. We voluntarily install to Miami-Dade HVHZ spec across Lantana for insurance-discount eligibility.',
  },
  'lauderdale-by-the-sea': {
    city: 'Lauderdale-By-The-Sea', county: 'Broward', hvhz: true,
    neighborhoods: ['LBTS oceanfront condos', 'Bel Air', 'Terra Mar Island'],
    zips: ['33308'],
    landmarks: ['Anglin\'s Fishing Pier', 'LBTS downtown', 'A1A oceanfront'],
    localHook: 'Lauderdale-By-The-Sea is a tiny oceanfront town heavy on condo and small commercial roofs east of A1A. Direct ocean exposure plus salt air drives our use of marine-grade fasteners on every LBTS re-roof.',
  },
  'lauderdale-lakes': {
    city: 'Lauderdale Lakes', county: 'Broward', hvhz: true,
    neighborhoods: ['Cypress Chase', 'Hawaiian Gardens', 'Somerset Place'],
    zips: ['33311', '33313', '33319'],
    landmarks: ['Lauderdale Lakes City Hall', 'Oakland Park Boulevard', 'State Road 7'],
    localHook: 'Lauderdale Lakes has a heavy 55+ community concentration in Hawaiian Gardens and Cypress Chase. We coordinate HOA-managed re-roof projects and run them to HVHZ spec across the entire community on a unified schedule.',
  },
  'lauderhill': {
    city: 'Lauderhill', county: 'Broward', hvhz: true,
    neighborhoods: ['Inverrary', 'Bayside Court', 'Lauderhill Mall area', 'St James Park'],
    zips: ['33311', '33313', '33319', '33321', '33351'],
    landmarks: ['Inverrary Country Club', 'Lauderhill Performing Arts Center', 'Sunrise Boulevard corridor'],
    localHook: 'Lauderhill has the iconic Inverrary 55+ community plus established single-family stock. We re-roof both ends — HOA-coordinated tile work in Inverrary and individual residential replacements throughout the rest of the city.',
  },
  'lighthouse-point': {
    city: 'Lighthouse Point', county: 'Broward', hvhz: true,
    neighborhoods: ['South Lighthouse Point', 'North Lighthouse Point', 'Coral Key', 'Cap\'s Place area'],
    zips: ['33064'],
    landmarks: ['Hillsboro Inlet Lighthouse', 'Cap\'s Place island restaurant', 'Hillsboro Mile waterfront'],
    localHook: 'Lighthouse Point is a 2.4 sq-mi waterfront city with concentrated affluence and direct Atlantic exposure. Roof market skews to Spanish tile and standing-seam metal on waterfront homes. We install to HVHZ spec with reinforced ridge attachment for salt-air longevity.',
  },
  'margate': {
    city: 'Margate', county: 'Broward', hvhz: true,
    neighborhoods: ['Carolina Estates', 'Holiday Springs Village', 'Oriole Estates', 'Carolina Square'],
    zips: ['33063', '33068', '33073', '33093'],
    landmarks: ['Margate City Hall', 'Sample Road corridor', 'State Road 7'],
    localHook: 'Margate has substantial 55+ HOA community inventory plus older single-family stock from the 1970s. We re-roof both — HOA-coordinated tile and metal work in the 55+ communities and HVHZ-spec residential replacements throughout.',
  },
  'north-lauderdale': {
    city: 'North Lauderdale', county: 'Broward', hvhz: true,
    neighborhoods: ['Kimberly Forest', 'Pinewood', 'Broadlands', 'Hampton Pines'],
    zips: ['33068'],
    landmarks: ['Kimberly Boulevard', 'Rock Island Road', 'McNab Road'],
    localHook: 'North Lauderdale is dominated by 1970s and 1980s tract construction. We know the truss profiles in Kimberly Forest and Pinewood, the original plywood decking conditions, and the typical structural finds when we tear off these aging shingle roofs.',
  },
  'north-palm-beach': {
    city: 'North Palm Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Lost Tree Village', 'North Palm Beach Country Club', 'Old Port Cove'],
    zips: ['33408'],
    landmarks: ['John D. MacArthur Beach State Park', 'North Palm Beach Country Club', 'A1A corridor'],
    localHook: 'North Palm Beach has Lost Tree Village (one of South Florida\'s most exclusive private golf communities) plus mainstream country-club stock. Roof market is high-end tile and metal. We install to HVHZ spec for direct Atlantic exposure protection.',
  },
  'oakland-park': {
    city: 'Oakland Park', county: 'Broward', hvhz: true,
    neighborhoods: ['Coral Heights', 'Lake Estates', 'Royal Palm Acres', 'Bayview'],
    zips: ['33304', '33306', '33308', '33309', '33311', '33334'],
    landmarks: ['Cypress Creek industrial corridor', 'Oakland Park Boulevard', 'NE 38th Street'],
    localHook: 'Oakland Park has a heavier-than-average flat-roof inventory because of its mid-century housing stock. We run TPO PVC and modified bitumen here alongside the steep-slope replacements.',
  },
  'ocean-ridge': {
    city: 'Ocean Ridge', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Inlet Cay', 'Ocean Ridge oceanfront estates', 'Spanish River Park area'],
    zips: ['33435'],
    landmarks: ['Boynton Inlet', 'A1A oceanfront corridor'],
    localHook: 'Ocean Ridge is a tiny ultra-affluent barrier-island town. Direct Atlantic exposure on million-dollar estates drives our use of premium NOA tile and stainless-steel ridge and hip attachment hardware.',
  },
  'palm-beach': {
    city: 'Palm Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Estates Section', 'Midtown', 'Sea Streets', 'Bingham Island', 'Everglades Club area'],
    zips: ['33480'],
    landmarks: ['Worth Avenue', 'The Breakers', 'Mar-a-Lago', 'A1A waterfront'],
    localHook: 'Palm Beach is the ultra-premium tier of South Florida roofing. Spanish tile dominates with hand-selected color matching and historic-spec ridge details. We install to voluntary HVHZ spec with concierge-level scheduling around tenant occupancy and seasonal events.',
  },
  'pembroke-park': {
    city: 'Pembroke Park', county: 'Broward', hvhz: true,
    neighborhoods: ['Lake Shore mobile home park area', 'Pembroke Park main area'],
    zips: ['33009', '33023'],
    landmarks: ['Pembroke Road corridor', 'Hallandale Beach Boulevard'],
    localHook: 'Pembroke Park is a small inland municipality with substantial mobile-home and manufactured-housing inventory plus dense townhome stock. We carry the dual license and HVHZ certification required for both ends of the market.',
  },
  'royal-palm-beach': {
    city: 'Royal Palm Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Royal Palm Estates', 'La Mancha', 'Crestwood', 'The Acreage border'],
    zips: ['33411', '33421'],
    landmarks: ['Commons Park', 'Royal Palm Beach Community High School', 'Southern Boulevard'],
    localHook: 'Royal Palm Beach has substantial 1990s and 2000s tract construction now reaching original-roof end-of-life. We re-roof at scale across Royal Palm communities and voluntarily install to Miami-Dade HVHZ spec for insurance benefits.',
  },
  'sea-ranch-lakes': {
    city: 'Sea Ranch Lakes', county: 'Broward', hvhz: true,
    neighborhoods: ['Sea Ranch Lakes (the whole village is one community)'],
    zips: ['33308'],
    landmarks: ['Sea Ranch Lakes private beach', 'A1A corridor'],
    localHook: 'Sea Ranch Lakes is a tiny private gated waterfront village just south of Pompano Beach. Direct ocean exposure with HOA-coordinated re-roof cycles. We work the architectural-review process and install to HVHZ spec across the community.',
  },
  'southwest-ranches': {
    city: 'Southwest Ranches', county: 'Broward', hvhz: true,
    neighborhoods: ['Sunshine Ranches', 'Whisper Walk', 'Rolling Oaks Ranches'],
    zips: ['33330', '33331', '33332'],
    landmarks: ['Griffin Road corridor', 'Volunteer Park'],
    localHook: 'Southwest Ranches is dominated by acreage estate homes with stables, large barns, and ranch-style architecture. Roof market is high-end metal and tile with custom flashing and complex geometry. We handle the structural-licensing requirement that ranch barn re-roofs often need.',
  },
  'tamarac': {
    city: 'Tamarac', county: 'Broward', hvhz: true,
    neighborhoods: ['Kings Point', 'Mainlands', 'Westwood', 'Woodmont', 'Sunflower Heathgate'],
    zips: ['33319', '33321', '33351'],
    landmarks: ['Tamarac City Hall', 'Woodmont Country Club', 'Commercial Boulevard'],
    localHook: 'Tamarac has one of the densest 55+ HOA-community concentrations in Broward, especially Kings Point. We coordinate HOA-approved tile and metal re-roof cycles across multiple communities at HVHZ spec.',
  },
  'west-palm-beach': {
    city: 'West Palm Beach', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Flamingo Park', 'Old Northwood', 'El Cid', 'SoSo', 'Northwood Shores', 'Hillcrest'],
    zips: ['33401', '33405', '33406', '33407', '33409', '33411', '33412', '33413', '33415', '33417'],
    landmarks: ['CityPlace', 'Clematis Street', 'Norton Museum of Art', 'Palm Beach International Airport'],
    localHook: 'West Palm Beach housing stock ranges from 1920s Mediterranean Revival in El Cid to mid-century ranch in Flamingo Park to modern lofts downtown. We work the city building department on Banyan Boulevard and know the historic-overlay re-roof requirements in Old Northwood.',
  },
  'westlake': {
    city: 'Westlake', county: 'Palm Beach', hvhz: false,
    neighborhoods: ['Westlake (a single planned community)'],
    zips: ['33470'],
    landmarks: ['Seminole Pratt Whitney Road', 'Westlake City Hall'],
    localHook: 'Westlake is a brand-new planned community in western Palm Beach County (incorporated 2016). Almost all original-construction roofs — minimal current re-roof demand, but we serve Westlake for inspections, leak repairs, and new-home roof additions.',
  },
  'weston': {
    city: 'Weston', county: 'Broward', hvhz: true,
    neighborhoods: ['Bonaventure', 'Weston Hills', 'Country Isles', 'Savanna', 'The Falls'],
    zips: ['33326', '33327', '33331', '33332'],
    landmarks: ['Weston Town Center', 'Markham Park', 'I-75 corridor'],
    localHook: 'Weston is dominated by 1990s and 2000s gated communities like Weston Hills, Bonaventure, and The Falls. Tile and high-end metal re-roofs predominate. We work the HOA architectural-review processes that govern every Weston re-roof.',
  },
  'wilton-manors': {
    city: 'Wilton Manors', county: 'Broward', hvhz: true,
    neighborhoods: ['Wilton Estates', 'Westwood Heights', 'Andrews Gardens', 'Coral Garden Isles'],
    zips: ['33305', '33311', '33334'],
    landmarks: ['Wilton Drive', 'Hagen Park', 'East Las Olas Boulevard'],
    localHook: 'Wilton Manors is dominated by 1950s and 1960s mid-century modern and ranch homes. We work the historic-overlay re-roof considerations and specialize in low-slope flat and tapered-insulation roofs common in mid-century MiMo construction.',
  },
};

// Also pull from cities.json for cities not in ENRICHMENT
const CITIES_FALLBACK: Record<string, { city: string }> = {};
for (const c of cities as Array<{ slug: string; city: string }>) {
  CITIES_FALLBACK[c.slug] = { city: c.city };
}

export function getCityEnrichment(slug: string): CityEnrichment | null {
  const data = ENRICHMENT[slug];
  if (data) {
    return { slug, ...data };
  }
  const fallback = CITIES_FALLBACK[slug];
  if (fallback) {
    return {
      slug,
      city: fallback.city,
      county: 'South Florida',
      hvhz: false,
    };
  }
  return null;
}
